### PR TITLE
Fix npm package versioning

### LINKED ISSUE #106: Potential issue with npm `LossyFeedEvent` & versioning
For a given snapshot of the npm endpoint https://registry.npmjs.org/-/rss the assumption that entries are in chronological order to their respective `pubDate` doesn't seem to be valid. As can be seen below  `ngx-jira-issue-collector` has a `pubDate` of `Tue, 02 Jun 2020 08:37:26 GMT` nestled between the 7th May 2021 dates, and other occurrences can be seen.

This presents an issue when applying the `findOverlap` logic for the lossy logging, as this relies on using the oldest pkg of any given polling set as a marker for triggering the event.

<details>
  <summary>npm rss snapshot</summary>

```
<?xml version="1.0" encoding="UTF-8"?><rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
    <channel>
        <title><![CDATA[npm recent updates]]></title>
        <description><![CDATA[Updates to the npm package registry]]></description>
        <link>https://www.npmjs.com/</link>
        <generator>RSS for Node</generator>
        <lastBuildDate>Fri, 07 May 2021 12:17:52 GMT</lastBuildDate>
        <atom:link href="https://registry.npmjs.org/-/rss" rel="self" type="application/rss+xml"/>
        <pubDate>Fri, 07 May 2021 12:17:52 GMT</pubDate>
        <language><![CDATA[en]]></language>
        <ttl>600</ttl>
        <item>
            <title><![CDATA[@100mslive/sdk-components]]></title>
            <description><![CDATA[Congrats! You just saved yourself hours of work by bootstrapping this project with TSDX. Letâ€™s get you oriented with whatâ€™s here and how to use it.]]></description>
            <link>https://npmjs.com/package/@100mslive/sdk-components</link>
            <guid isPermaLink="true">https://npmjs.com/package/@100mslive/sdk-components</guid>
            <dc:creator><![CDATA[aniket100ms]]></dc:creator>
            <pubDate>Fri, 07 May 2021 11:56:20 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[ngx-jira-issue-collector]]></title>
            <description><![CDATA[Jira Issue Collector as an angular component]]></description>
            <link>https://npmjs.com/package/ngx-jira-issue-collector</link>
            <guid isPermaLink="true">https://npmjs.com/package/ngx-jira-issue-collector</guid>
            <dc:creator><![CDATA[kbjerke]]></dc:creator>
            <pubDate>Tue, 02 Jun 2020 08:37:26 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@learnthis/nest-cqrs]]></title>
            <link>https://npmjs.com/package/@learnthis/nest-cqrs</link>
            <guid isPermaLink="true">https://npmjs.com/package/@learnthis/nest-cqrs</guid>
            <dc:creator><![CDATA[desarrolloutil]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:17:33 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[mio-common-js]]></title>
            <description><![CDATA[å…¬ç”¨jså·¥å…·åº“]]></description>
            <link>https://npmjs.com/package/mio-common-js</link>
            <guid isPermaLink="true">https://npmjs.com/package/mio-common-js</guid>
            <dc:creator><![CDATA[miofly]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:17:28 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[html-converter-full]]></title>
            <description><![CDATA[Utility functions that convert your string into a safely sanitized html]]></description>
            <link>https://npmjs.com/package/html-converter-full</link>
            <guid isPermaLink="true">https://npmjs.com/package/html-converter-full</guid>
            <dc:creator><![CDATA[baze5]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:17:28 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@cognite/sdk-wells]]></title>
            <description><![CDATA[Cognite wells SDK is tool for interacting with the CDF Wells Data Layer (WDL). All queries are passed through a service API called the 'Well-Service' that handles ingestion and queries into the well data layer.]]></description>
            <link>https://npmjs.com/package/@cognite/sdk-wells</link>
            <guid isPermaLink="true">https://npmjs.com/package/@cognite/sdk-wells</guid>
            <dc:creator><![CDATA[cognitecicd]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:17:23 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[droff]]></title>
            <description><![CDATA[A Discord client powered by RxJS and `discord-api-types`]]></description>
            <link>https://npmjs.com/package/droff</link>
            <guid isPermaLink="true">https://npmjs.com/package/droff</guid>
            <dc:creator><![CDATA[tim-smart]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:17:25 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@imtf/rjsf-conditionals]]></title>
            <description><![CDATA[Extension of @rjsf/core with conditional field support]]></description>
            <link>https://npmjs.com/package/@imtf/rjsf-conditionals</link>
            <guid isPermaLink="true">https://npmjs.com/package/@imtf/rjsf-conditionals</guid>
            <dc:creator><![CDATA[dev-management]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:17:24 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@laufire/utils]]></title>
            <description><![CDATA[A simple set of utility libraries to ease development.]]></description>
            <link>https://npmjs.com/package/@laufire/utils</link>
            <guid isPermaLink="true">https://npmjs.com/package/@laufire/utils</guid>
            <dc:creator><![CDATA[laufire]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:17:18 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[eslint-plugin-ghost]]></title>
            <description><![CDATA[Shared eslint configurations]]></description>
            <link>https://npmjs.com/package/eslint-plugin-ghost</link>
            <guid isPermaLink="true">https://npmjs.com/package/eslint-plugin-ghost</guid>
            <dc:creator><![CDATA[erisds]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:17:16 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[terrapin-test-1]]></title>
            <link>https://npmjs.com/package/terrapin-test-1</link>
            <guid isPermaLink="true">https://npmjs.com/package/terrapin-test-1</guid>
            <dc:creator><![CDATA[dorfire]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:17:10 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@crystaldesign/diva]]></title>
            <description><![CDATA[A webcomponent that allows you to add all products of the DIVA universe to your webpage.]]></description>
            <link>https://npmjs.com/package/@crystaldesign/diva</link>
            <guid isPermaLink="true">https://npmjs.com/package/@crystaldesign/diva</guid>
            <dc:creator><![CDATA[crystaldesign]]></dc:creator>
            <pubDate>Wed, 07 Apr 2021 07:50:17 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@crystaldesign/diva-react]]></title>
            <description><![CDATA[A react component that allows you to add all products of the DIVA universe to your webpage.]]></description>
            <link>https://npmjs.com/package/@crystaldesign/diva-react</link>
            <guid isPermaLink="true">https://npmjs.com/package/@crystaldesign/diva-react</guid>
            <dc:creator><![CDATA[crystaldesign]]></dc:creator>
            <pubDate>Wed, 07 Apr 2021 07:50:17 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@crystaldesign/diva-framework]]></title>
            <link>https://npmjs.com/package/@crystaldesign/diva-framework</link>
            <guid isPermaLink="true">https://npmjs.com/package/@crystaldesign/diva-framework</guid>
            <dc:creator><![CDATA[crystaldesign]]></dc:creator>
            <pubDate>Wed, 07 Apr 2021 07:50:11 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[starstuff-style]]></title>
            <description><![CDATA[Opinionated, yet simple, base stylesheet]]></description>
            <link>https://npmjs.com/package/starstuff-style</link>
            <guid isPermaLink="true">https://npmjs.com/package/starstuff-style</guid>
            <dc:creator><![CDATA[keplersj]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:17:05 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@native-html/transient-render-engine]]></title>
            <description><![CDATA[An engine which produces an intermediary structure from HTML to create a React Native render tree.]]></description>
            <link>https://npmjs.com/package/@native-html/transient-render-engine</link>
            <guid isPermaLink="true">https://npmjs.com/package/@native-html/transient-render-engine</guid>
            <dc:creator><![CDATA[jsamr]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:17:05 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@bugsnag/js]]></title>
            <description><![CDATA[Universal Javascript error reporting. Automatically detect JavaScript errors in the browser and Node.js, with plugins for React, Vue, Angular, Express, Restify and Koa.]]></description>
            <link>https://npmjs.com/package/@bugsnag/js</link>
            <guid isPermaLink="true">https://npmjs.com/package/@bugsnag/js</guid>
            <dc:creator><![CDATA[bengourley]]></dc:creator>
            <pubDate>Tue, 06 Apr 2021 09:39:46 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@bugsnag/electron]]></title>
            <description><![CDATA[@bugsnag/electron notifier]]></description>
            <link>https://npmjs.com/package/@bugsnag/electron</link>
            <guid isPermaLink="true">https://npmjs.com/package/@bugsnag/electron</guid>
            <dc:creator><![CDATA[bengourley]]></dc:creator>
            <pubDate>Mon, 26 Apr 2021 13:54:31 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[abstract-type]]></title>
            <description><![CDATA[The abstract-type library includes the abstract `Type` class and `Value` class for streamable type info and validating value.]]></description>
            <link>https://npmjs.com/package/abstract-type</link>
            <guid isPermaLink="true">https://npmjs.com/package/abstract-type</guid>
            <dc:creator><![CDATA[riceball]]></dc:creator>
            <pubDate>Sun, 06 Mar 2016 13:59:29 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@bugsnag/node]]></title>
            <description><![CDATA[Bugsnag error reporter for Node.js]]></description>
            <link>https://npmjs.com/package/@bugsnag/node</link>
            <guid isPermaLink="true">https://npmjs.com/package/@bugsnag/node</guid>
            <dc:creator><![CDATA[bengourley]]></dc:creator>
            <pubDate>Tue, 06 Apr 2021 09:39:38 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@bugsnag/plugin-electron-renderer-event-data]]></title>
            <description><![CDATA[@bugsnag/electron plugin to get fully populated event data in renderer callbacks]]></description>
            <link>https://npmjs.com/package/@bugsnag/plugin-electron-renderer-event-data</link>
            <guid isPermaLink="true">https://npmjs.com/package/@bugsnag/plugin-electron-renderer-event-data</guid>
            <dc:creator><![CDATA[bengourley]]></dc:creator>
            <pubDate>Mon, 26 Apr 2021 13:53:58 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@bugsnag/plugin-stackframe-path-normaliser]]></title>
            <description><![CDATA[@bugsnag/js plugin to normalise file paths in stackframes]]></description>
            <link>https://npmjs.com/package/@bugsnag/plugin-stackframe-path-normaliser</link>
            <guid isPermaLink="true">https://npmjs.com/package/@bugsnag/plugin-stackframe-path-normaliser</guid>
            <dc:creator><![CDATA[imjoehaines]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:16:48 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@bugsnag/plugin-angular]]></title>
            <description><![CDATA[Angular integration for bugsnag-js]]></description>
            <link>https://npmjs.com/package/@bugsnag/plugin-angular</link>
            <guid isPermaLink="true">https://npmjs.com/package/@bugsnag/plugin-angular</guid>
            <dc:creator><![CDATA[bengourley]]></dc:creator>
            <pubDate>Tue, 06 Apr 2021 09:38:41 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@bugsnag/plugin-electron-app]]></title>
            <description><![CDATA[@bugsnag/electron plugin to collect app information]]></description>
            <link>https://npmjs.com/package/@bugsnag/plugin-electron-app</link>
            <guid isPermaLink="true">https://npmjs.com/package/@bugsnag/plugin-electron-app</guid>
            <dc:creator><![CDATA[bengourley]]></dc:creator>
            <pubDate>Mon, 26 Apr 2021 13:53:51 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[ad-kernel]]></title>
            <description><![CDATA[## Project setup ``` npm install ``` ### Compiles and hot-reloads and mock data for development ``` npm run mock ```]]></description>
            <link>https://npmjs.com/package/ad-kernel</link>
            <guid isPermaLink="true">https://npmjs.com/package/ad-kernel</guid>
            <dc:creator><![CDATA[chengaohe45]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:16:38 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[smartapp-automator]]></title>
            <description><![CDATA[###### [API æ–‡æ¡£](./docs/api/Menu.md)]]></description>
            <link>https://npmjs.com/package/smartapp-automator</link>
            <guid isPermaLink="true">https://npmjs.com/package/smartapp-automator</guid>
            <dc:creator><![CDATA[sharenaive]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:16:38 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[tailwindcss-language-service]]></title>
            <link>https://npmjs.com/package/tailwindcss-language-service</link>
            <guid isPermaLink="true">https://npmjs.com/package/tailwindcss-language-service</guid>
            <dc:creator><![CDATA[bradlc]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:16:37 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@native-html/css-processor]]></title>
            <description><![CDATA[An inline CSS processor to translate CSS properties to React Native styles.]]></description>
            <link>https://npmjs.com/package/@native-html/css-processor</link>
            <guid isPermaLink="true">https://npmjs.com/package/@native-html/css-processor</guid>
            <dc:creator><![CDATA[jsamr]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:16:35 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[stocache]]></title>
            <description><![CDATA[local storage cache]]></description>
            <link>https://npmjs.com/package/stocache</link>
            <guid isPermaLink="true">https://npmjs.com/package/stocache</guid>
            <dc:creator><![CDATA[dalirnet]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:16:23 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[rnjs-core]]></title>
            <description><![CDATA[Rich NodeJS Framework.]]></description>
            <link>https://npmjs.com/package/rnjs-core</link>
            <guid isPermaLink="true">https://npmjs.com/package/rnjs-core</guid>
            <dc:creator><![CDATA[artgou]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:16:11 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[whistle-sdk]]></title>
            <description><![CDATA[SDK for whistle]]></description>
            <link>https://npmjs.com/package/whistle-sdk</link>
            <guid isPermaLink="true">https://npmjs.com/package/whistle-sdk</guid>
            <dc:creator><![CDATA[helinjiang]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:15:40 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[stylelint-variable-check-teamix]]></title>
            <description><![CDATA[A stylelint custom rule to check the use of css variable on declaration.]]></description>
            <link>https://npmjs.com/package/stylelint-variable-check-teamix</link>
            <guid isPermaLink="true">https://npmjs.com/package/stylelint-variable-check-teamix</guid>
            <dc:creator><![CDATA[cyris]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:15:59 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[rn-bottom-test]]></title>
            <description><![CDATA[This is testing purpose]]></description>
            <link>https://npmjs.com/package/rn-bottom-test</link>
            <guid isPermaLink="true">https://npmjs.com/package/rn-bottom-test</guid>
            <dc:creator><![CDATA[lockybanna123]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:15:47 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@xflr6/chatbot-engine]]></title>
            <description><![CDATA[Extraction of core engine from chatbot]]></description>
            <link>https://npmjs.com/package/@xflr6/chatbot-engine</link>
            <guid isPermaLink="true">https://npmjs.com/package/@xflr6/chatbot-engine</guid>
            <dc:creator><![CDATA[svkanoria]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:15:44 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[bimplus-renderer]]></title>
            <description><![CDATA[bim+ renderer]]></description>
            <link>https://npmjs.com/package/bimplus-renderer</link>
            <guid isPermaLink="true">https://npmjs.com/package/bimplus-renderer</guid>
            <dc:creator><![CDATA[bimplus]]></dc:creator>
            <pubDate>Mon, 26 Apr 2021 12:54:22 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@flowplayer/player]]></title>
            <description><![CDATA[video player for the future]]></description>
            <link>https://npmjs.com/package/@flowplayer/player</link>
            <guid isPermaLink="true">https://npmjs.com/package/@flowplayer/player</guid>
            <dc:creator><![CDATA[nnarhinen]]></dc:creator>
            <pubDate>Fri, 23 Apr 2021 13:16:36 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[ublo]]></title>
            <link>https://npmjs.com/package/ublo</link>
            <guid isPermaLink="true">https://npmjs.com/package/ublo</guid>
            <dc:creator><![CDATA[jean_tinland]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:15:13 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[homebridge-ewelink]]></title>
            <description><![CDATA[Homebridge plugin to control eWeLink devices.]]></description>
            <link>https://npmjs.com/package/homebridge-ewelink</link>
            <guid isPermaLink="true">https://npmjs.com/package/homebridge-ewelink</guid>
            <dc:creator><![CDATA[bwp91]]></dc:creator>
            <pubDate>Fri, 07 May 2021 05:36:53 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[tinkiet]]></title>
            <description><![CDATA[Pragmatic UI Web Components]]></description>
            <link>https://npmjs.com/package/tinkiet</link>
            <guid isPermaLink="true">https://npmjs.com/package/tinkiet</guid>
            <dc:creator><![CDATA[eskan]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:15:11 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@xflr6/chatbot]]></title>
            <description><![CDATA[A framework for creating and executing "canned" chatbots]]></description>
            <link>https://npmjs.com/package/@xflr6/chatbot</link>
            <guid isPermaLink="true">https://npmjs.com/package/@xflr6/chatbot</guid>
            <dc:creator><![CDATA[svkanoria]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:15:07 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@gapizza/eslint-config]]></title>
            <description><![CDATA[General purpose Node ESLint configuration]]></description>
            <link>https://npmjs.com/package/@gapizza/eslint-config</link>
            <guid isPermaLink="true">https://npmjs.com/package/@gapizza/eslint-config</guid>
            <dc:creator><![CDATA[ehacke]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:15:00 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[cra-template-timiodulate]]></title>
            <description><![CDATA[timiodulate Create React App template.]]></description>
            <link>https://npmjs.com/package/cra-template-timiodulate</link>
            <guid isPermaLink="true">https://npmjs.com/package/cra-template-timiodulate</guid>
            <dc:creator><![CDATA[timiodulate]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:14:52 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@switchboard-xyz/switchboard-api]]></title>
            <description><![CDATA[A library for the Switchboard Oracle Network.]]></description>
            <link>https://npmjs.com/package/@switchboard-xyz/switchboard-api</link>
            <guid isPermaLink="true">https://npmjs.com/package/@switchboard-xyz/switchboard-api</guid>
            <dc:creator><![CDATA[mgild]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:14:47 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[react-native-set-wallpaper]]></title>
            <description><![CDATA[Sets wallpaper with react-native]]></description>
            <link>https://npmjs.com/package/react-native-set-wallpaper</link>
            <guid isPermaLink="true">https://npmjs.com/package/react-native-set-wallpaper</guid>
            <dc:creator><![CDATA[siddsarkar]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:14:47 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[schummar-translate]]></title>
            <link>https://npmjs.com/package/schummar-translate</link>
            <guid isPermaLink="true">https://npmjs.com/package/schummar-translate</guid>
            <dc:creator><![CDATA[schummar]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:14:41 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[dejquery.co]]></title>
            <description><![CDATA[a new jsco]]></description>
            <link>https://npmjs.com/package/dejquery.co</link>
            <guid isPermaLink="true">https://npmjs.com/package/dejquery.co</guid>
            <dc:creator><![CDATA[hydeedu]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:14:35 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@vitalyrudenko/dependency-registry]]></title>
            <description><![CDATA[Tiny JavaScript dependency registry]]></description>
            <link>https://npmjs.com/package/@vitalyrudenko/dependency-registry</link>
            <guid isPermaLink="true">https://npmjs.com/package/@vitalyrudenko/dependency-registry</guid>
            <dc:creator><![CDATA[vitaly-rudenko]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:14:28 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[honeyfield-component-library]]></title>
            <description><![CDATA[This library was generated with [Angular CLI](https://github.com/angular/angular-cli) version 9.0.0.]]></description>
            <link>https://npmjs.com/package/honeyfield-component-library</link>
            <guid isPermaLink="true">https://npmjs.com/package/honeyfield-component-library</guid>
            <dc:creator><![CDATA[lojpadejan1]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:14:27 GMT</pubDate>
        </item>
        <item>
            <title><![CDATA[@jolie/jpm]]></title>
            <description><![CDATA[The Jolie Package Manager]]></description>
            <link>https://npmjs.com/package/@jolie/jpm</link>
            <guid isPermaLink="true">https://npmjs.com/package/@jolie/jpm</guid>
            <dc:creator><![CDATA[fmontesi]]></dc:creator>
            <pubDate>Fri, 07 May 2021 12:14:20 GMT</pubDate>
        </item>
    </channel>
</rss>
```
</details>

### PR DESCRIPTION
**Pull request by tom--pollard**
Resolves #106 

The assumption that `pubDate` reported on the main rss feed is that of the `latest` dist-tag is only always valid when there are no other dist-tags for the package. The feed event can be triggered by any of the listed dist-tags updating. Additional dist-tags can be given arbitrary names, as such each tag has to be checked to find which has most recent timestamp.

### CODE REVIEW

**Comment by tom--pollard** [comment]
This requires adding the necessary metadata responses to the testcases still

**Comment by tom--pollard** [comment]
Tests updated

File: feeds/npm/npm.go [hunk 1]
```diff
@@ -75,19 +50,49 @@ func fetchPackages() ([]*Package, error) {
...
-		return "", err
+		return nil, err
 	}
 	defer resp.Body.Close()
-	v := &PackageVersion{}
-	err = json.NewDecoder(resp.Body).Decode(v)
+	body, err := ioutil.ReadAll(resp.Body)
 	if err != nil {
-		return "", err
+		return nil, err
```
Comment (Qinusty) [inline feeds/npm/npm.go:62]: We should probably wrap these errors with errJson for additional context.

File: feeds/npm/npm.go [hunk 2]
```diff
@@ -75,19 +50,49 @@ func fetchPackages() ([]*Package, error) {
...
+	}
+	var jsonMap map[string]interface{}
+	err = json.Unmarshal(body, &jsonMap)
+	if err != nil {
+		return nil, err
+	}
+	distTags, ok := jsonMap["dist-tags"].(map[string]interface{})
+	if !ok {
+		return nil, errJSON
```
Comment (Qinusty) [inline feeds/npm/npm.go:71]: We can wrap this with some additional detail referencing the field we failed to extract.

File: feeds/npm/npm.go [hunk 3]
```diff
@@ -75,19 +50,49 @@ func fetchPackages() ([]*Package, error) {
...
+	for _, v := range distTags {
+		versionString, ok := v.(string)
+		if !ok {
+			return nil, errJSON
+		}
+		date, err := time.Parse(time.RFC3339, versions[versionString].(string))
+		if err != nil {
+			return nil, err
+		}
+		if pkg.CreatedDate.IsZero() {
```
Comment (Qinusty) [inline feeds/npm/npm.go:87]: Can these two statements be merged to remove the duplication?

File: feeds/npm/npm_test.go [hunk 4]
```diff
@@ -40,11 +41,41 @@ func TestNpmLatest(t *testing.T) {
...
+	if err != nil {
+		t.Errorf("time.Parse returned error: %v", err)
+	}
+	if !pkgs[1].CreatedDate.Equal(barTime) {
+		t.Errorf("Unexpected created date `%s` found in place of expected `2021-05-11T17:23:02.000Z`", pkgs[1].CreatedDate)
+	}
+
+	bazTime, err := time.Parse(time.RFC3339, "2021-05-11T14:18:32.000Z")
+	if err != nil {
+		t.Errorf("time.Parse returned error: %v", err)
```
Comment (Qinusty) [inline feeds/npm/npm_test.go:75]: This should be Fatalf as we cannot continue if this fails. There are a few other cases of this in this test.

File: feeds/npm/npm_test.go [hunk 5]
```diff
@@ -98,7 +141,31 @@ func barVersionInfoResponse(w http.ResponseWriter, r *http.Request) {
...
+	}
+}
+`))
+	if err != nil {
+		fmt.Println("Unexpected error during mock http server write: %w", err)
+	}
+}
+
+func bazVersionInfoResponse(w http.ResponseWriter, r *http.Request) {
+	_, err := w.Write([]byte(`
```
Comment (Qinusty) [inline feeds/npm/npm_test.go:160]: Does this err not need checking to satisfy the linter?

File: feeds/npm/npm.go [hunk 6]
```diff
@@ -75,19 +50,49 @@ func fetchPackages() ([]*Package, error) {
 	return rssResponse.Packages, nil
```
Comment (Qinusty) [inline feeds/npm/npm.go:50]: This is slightly misleading now since we're only extracting the PKG name from title. Should we just return a collection of strings?

File: feeds/npm/npm.go [hunk 7]
```diff
@@ -75,19 +50,49 @@ func fetchPackages() ([]*Package, error) {
...
+			return nil, errJSON
+		}
+		date, err := time.Parse(time.RFC3339, versions[versionString].(string))
+		if err != nil {
+			return nil, err
+		}
+		if pkg.CreatedDate.IsZero() {
+			pkg.CreatedDate = date
+			pkg.Version = versionString
+		} else if date.After(pkg.CreatedDate) {
```
Comment (Qinusty) [inline feeds/npm/npm.go:90]: Do we want anything after the date in the RSS feed? Or do we want the most recent? Is there a case where we have multiple dist tags updated since the pubDate in the RSS feed?

Comment (tom--pollard) [reply feeds/npm/npm.go:90]: There is certainly a case where multiple dist-tags could have updated within the windows of results we get from polling. I've gone for taking the most recent of the tags. This obviously could give you a scenario where the same tag is reported multiple times if the main rss feed has multiple entries for the same package (as it would do now, you'd get the value of latest multiple times). Without referencing against the current polls package name list for duplicates I'm not sure how we'd handle this. The `pubDate` in the rss feed cannot be relied on for anything.

File: feeds/npm/npm.go (hunk 6 above)
Comment (tom--pollard) [reply feeds/npm/npm.go:50]: My personal preference would be that this func still generates the package structs, and then the version info is added in the seperate func. Happy to change it though if needs be.

File: feeds/npm/npm_test.go (hunk 5 above)
Comment (tom--pollard) [reply feeds/npm/npm_test.go:160]: It is checked on line `172`

File: feeds/npm/npm.go (hunk 3 above)
Comment (tom--pollard) [reply feeds/npm/npm.go:87]: I'm not sure what you mean here, what is checking if `time.Parse()` is returning an error on the json string, `pkg.CreatedDate.IsZero()` is checking if the pkg struct has a zero value for the field, in this case meaning the first iteration.

File: feeds/npm/npm.go (hunk 6 above)
Comment (Qinusty) [reply feeds/npm/npm.go:50]: Maybe some documentation could be added to the func to make it clear that the package is partially populated and is not sufficient without additional processing.

File: feeds/npm/npm.go (hunk 3 above)
Comment (Qinusty) [reply feeds/npm/npm.go:89]: `.IsZero` and `.After` both do the same logic in the case of True, these can be anded together.

**Review by Qinusty — APPROVED** [review]

File: feeds/npm/npm.go (hunk 3 above)
Comment (tom--pollard) [reply feeds/npm/npm.go:89]: Ah, I think I see what you mean, although I think in this case it's an `or`

File: feeds/npm/npm.go (hunk 6 above)
Comment (tom--pollard) [reply feeds/npm/npm.go:50]: Sure, done!

File: feeds/npm/npm.go (hunk 7 above)
Comment (tom--pollard) [reply feeds/npm/npm.go]: I'm going to try checking occurrences of the same package in a given poll set

Comment (tom--pollard) [reply feeds/npm/npm.go]: I've tried to handle this in a 'best we can' approach, see what you think

File: feeds/npm/npm.go [hunk 8]
```diff
@@ -117,16 +127,34 @@ func (feed Feed) Latest(cutoff time.Time) ([]*feeds.Package, error) {
...
 	}
 
+	// Handle the possibility of multiple releases of the same package
+	// within the polled `packages` slice.
+	uniquePackages := make(map[string][]*Package)
 	for _, pkg := range packages {
-		go func(pkg *Package) {
-			v, err := fetchVersionInformation(pkg.Title)
+		v, ok := uniquePackages[pkg.Title]
+		if ok {
```
Comment (Qinusty) [inline feeds/npm/npm.go:135]: I think this can be tidied with 
```
pkgs, ok := uniquePackages[pkg.Title]
if !ok {
  pkgs = []*Package{}
}
// Insert common append logic here
```

File: feeds/npm/npm_test.go (hunk 5 above)
Comment (Qinusty) [reply feeds/npm/npm_test.go:182]: Very worrying diff.....

File: feeds/npm/npm.go [hunk 9]
```diff
@@ -117,16 +127,34 @@ func (feed Feed) Latest(cutoff time.Time) ([]*feeds.Package, error) {
...
 				errs <- err
 				return
 			}
-			feedPkg := feeds.NewPackage(pkg.CreatedDate.Time, pkg.Title, v, FeedName)
-			packageChannel <- feedPkg
-		}(pkg)
+			for _, versionedPkg := range versionedPkgs {
+				feedPkg := feeds.NewPackage(versionedPkg.CreatedDate, versionedPkg.Title,
+					versionedPkg.Version, FeedName)
+				packageChannel <- feedPkg
```
Comment (Qinusty) [inline feeds/npm/npm.go:155]: Is `len(versionedPkgs) == len(packages)`?

Comment (tom--pollard) [reply feeds/npm/npm.go:155]: If you were to total the `versionedPkgs` from each iteration then yes, unless I've made a mistake

File: feeds/npm/npm.go [hunk 10]
```diff
@@ -73,22 +53,56 @@ func fetchPackages() ([]*Package, error) {
...
-	return rssResponse.Packages, nil
+	return rssResponse.PackageEvents, nil
 }
 
-// Gets the package version from the NPM.
-func fetchVersionInformation(packageName string) (string, error) {
-	resp, err := httpClient.Get(fmt.Sprintf("%s/%s", versionURL, packageName))
+// Gets the package version & corresponding created date from NPM. Returns
+// a slice of {}Package.
+func createPackages(pkgTitle string, count int) ([]*Package, error) {
```
Comment (Qinusty) [inline feeds/npm/npm.go:61]: NIT: create seems incorrect here since we're interacting with an external data source.

File: feeds/npm/npm.go (hunk 8 above)
Comment (tom--pollard) [reply feeds/npm/npm.go]: Changed the approach with the latest version, but thanks :)

File: feeds/npm/npm.go [hunk 11]
```diff
@@ -73,22 +53,56 @@ func fetchPackages() ([]*Package, error) {
...
+	for tag, value := range versions {
+		date, err := time.Parse(time.RFC3339, value.(string))
+		if err != nil {
+			return nil, err
+		}
+		tagSlice = append(tagSlice, &Package{Title: pkgTitle, CreatedDate: date, Version: tag})
+	}
+
+	// Sort slice of tags into order of most recent.
+	sort.SliceStable(tagSlice, func(i, j int) bool {
```
Comment (Qinusty) [inline feeds/npm/npm.go:101]: Do you want to throw in `feeds.SortPackages()` from [here](https://github.com/Qinusty/package-feeds/commit/2d500f0de1478fd16944666b5ae3c73282603551#diff-7c737d5ed17f49b3de045a735c3b8426c9b22a9fb2bd8832dc349e23ce0b8a0fR60-R65) since we're likely to be reusing this going forwards?

**Review by Qinusty — APPROVED** [review]
Two small suggestions, otherwise LGTM!

File: feeds/npm/npm.go (hunk 11 above)
Comment (tom--pollard) [reply feeds/npm/npm.go:101]: Sure, I'll add a commit for it

Comment (tom--pollard) [reply feeds/npm/npm.go:101]: Ah, not so simple. At this point they're not the correct type `[]*feeds.Package{}`

File: feeds/npm/npm.go (hunk 10 above)
Comment (tom--pollard) [reply feeds/npm/npm.go]: Fair point, changed it to `fetch` inline with the original naming,

**Comment by tom--pollard** [comment]
Having an instance of this running in the background just hit a hiccup when polling https://registry.npmjs.org/dsr-package-public-lobar-forme-ebbed-mixen that has a structure that is not expected.

```
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 149 [running]:
github.com/ossf/package-feeds/feeds/npm.fetchPackages(0xc0000388d0, 0x2a, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/app/feeds/npm/npm.go:94 +0xab7
github.com/ossf/package-feeds/feeds/npm.Feed.Latest.func1(0xc0000a4060, 0xc0000a4000, 0xc0000388d0, 0x2a, 0x1)
	/app/feeds/npm/npm.go:144 +0x65
created by github.com/ossf/package-feeds/feeds/npm.Feed.Latest
	/app/feeds/npm/npm.go:143 +0x254
```

**Comment by tom--pollard** [comment]
Testing the json output with a `dummy` package

Package created, and then deleted: 
```
{"_id":"dummypackagetest","name":"dummypackagetest","time":{"created":"2021-05-14T08:40:42.806Z","1.0.0":"2021-05-14T08:40:43.217Z","modified":"2021-05-14T08:56:27.660Z","1.1.0":"2021-05-14T08:42:45.013Z","1.2.0":"2021-05-14T08:55:42.264Z","unpublished":{"name":"cttpollard","time":"2021-05-14T08:56:27.659Z","tags":{"latest":"1.1.0","next":"1.2.0"},"versions":["1.1.0","1.2.0"],"maintainers":[{"name":"cttpollard","email":"tom.pollard@codethink.co.uk"}]}}}
```

Reupload of the package, with a new version after 24 hours:
```
{"_rev":"5-b5a662192832cbbd1d94be1b9f007357","time":{"1.1.0":"2021-05-14T08:56:27.659Z","1.2.0":"2021-05-14T08:56:27.659Z","created":"2021-05-17T09:47:32.081Z","2.0.0":"2021-05-17T09:47:32.212Z","modified":"2021-05-17T09:47:36.972Z"},"_id":"dummypackagetest","name":"dummypackagetest","dist-tags":{"latest":"2.0.0"},"versions":{"2.0.0":{"name":"dummypackagetest","version":"2.0.0","description":"test","main":"index.js","scripts":{"test":"echo \"Error: no test specified\" && exit 1"},"author":"","license":"ISC","dependencies":{"dummypackagetest":"^1.0.0"},"_id":"dummypackagetest@2.0.0","_nodeVersion":"12.21.0","_npmVersion":"7.5.2","dist":{"integrity":"sha512-T2qtAMtkSn96viDUuOCy97E6aMH4dkKu9lyh7Wd11FTqbLHHE8E5dea33zUrfqpLrVr3Top7anPnkV1evyF7NA==","shasum":"9fd04338e106810448f35b2427d1848e6ef08a7c","tarball":"https://registry.npmjs.org/dummypackagetest/-/dummypackagetest-2.0.0.tgz","fileCount":1,"unpackedSize":273,"npm-signature":"-----BEGIN PGP SIGNATURE-----\r\nVersion: OpenPGP.js v3.0.13\r\nComment:
```

The `unpublished` field is not retained, as such the logic can be simplified

File: feeds/npm/npm.go [hunk 12]
```diff
@@ -72,22 +55,70 @@ func fetchPackages(baseURL string) ([]*Package, error) {
...
+
+	// The json string `time` contains versions in date order, oldest to newest.
+	versions, ok := jsonMap["time"].(map[string]interface{})
+	if !ok {
+		return nil, fmt.Errorf("%w : 'time' not found for package %s ",
+			errJSON, pkgTitle)
+	}
+
+	// If `unpublished` exists in the version map then at a given point in time
+	// the package was 'entirely' removed, the packagEvent(s) received are for package
```
Comment (Qinusty) [inline feeds/npm/npm.go:87]: s/packagEvent/packageEvent

File: feeds/npm/npm.go [hunk 13]
```diff
@@ -72,22 +55,70 @@ func fetchPackages(baseURL string) ([]*Package, error) {
...
+	// versions that no longer exist. For a given 24h period no further versions can
+	// be uploaded, with any previous versions never being available again.
+	// https://www.npmjs.com/policies/unpublish
+	_, unPublished := versions["unpublished"]
+
+	if unPublished {
+		unPublishedPackages := []*Package{}
+		for i := 0; i < count; i++ {
+			unPublishedPackages = append(unPublishedPackages, &Package{Unpublished: true})
```
Comment (Qinusty) [inline feeds/npm/npm.go:96]: Do we not want to include package title information here? Whilst we're not using this data right now we might as well populate the Package struct with the known information.

File: feeds/npm/npm.go (hunk 12 above)
Comment (tom--pollard) [reply feeds/npm/npm.go]: Thanks!

File: feeds/npm/npm.go (hunk 13 above)
Comment (tom--pollard) [reply feeds/npm/npm.go]: Yeh agreed, no harm in doing so :)
